### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by HenrikBengtsson** [sfirke/packagemetrics#15]
Drive-by note: missing 
```r
Remotes: thierrygosselin/stackr
```
in DESCRIPTION

**Comment by ledell** [comment]
Also wondering if R 3.4.0 is a necessary [requirement](https://github.com/ropenscilabs/packagemetrics/blob/master/DESCRIPTION#L11), or can it be relaxed to an earlier version of R?

**Comment by sfirke** [comment]
Thanks both!  @HenrikBengtsson I added a dependency on https://github.com/lshep/stackr, and @ledell I backed it down to require R 3.3.0 ... do you think that's sufficient or should I try to go back further?

**Comment by bzkrouse** [comment]
Agreed, thank you!  

@sfirke & @ledell - unfortunately, since we're utilizing tools::CRAN_package_db()  (a function that's new to 3.4.0),  I don't think we have flexibility in the dependency at the moment.  Maybe we should consider scraping the info directly from CRAN instead.

**Comment by sfirke** [comment]
Whoops good catch, I'll revert that part

On May 28, 2017 9:38 PM, "Becca Krouse" <notifications@github.com> wrote:

Agreed, thank you!

@sfirke <https://github.com/sfirke> & @ledell <https://github.com/ledell> -
we're utilizing tools::CRAN_package_db(), a function that's new to 3.4.0,
so I don't think we have flexibility in the dependency.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ropenscilabs/packagemetrics/issues/15#issuecomment-304555126>,
or mute the thread

**Comment by ledell** [comment]
Thanks @bzkrouse and @sfirke.  Time for me to upgrade to 3.4.0!
